# Generated by Django 3.2.5 on 2021-07-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventTitle',
            new_name='EventTeg',
        ),
    ]
