# Generated by Django 3.2.5 on 2021-07-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210707_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='label',
        ),
    ]
